spring:
  datasource:
    #url: jdbc:h2:mem:testdb
    url: jdbc:h2:file:~/testdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: dbsql
    initialization-mode: always
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
        
server:
  port: ${PORT:8080}
  servlet:
    context-path: /designer
    
logging:
   level:
      org:
        atmosphere: warn